"use client";

import { FormEvent, useState } from "react";
type Comment = { id: string; body: string; createdAt: string | Date; user: { displayName: string } };
export default function SocialPanel({ artworkId, signedIn, initialLikes, initialLiked, initialComments }: { artworkId: string; signedIn: boolean; initialLikes: number; initialLiked: boolean; initialComments: Comment[] }) {
  const [likes, setLikes] = useState(initialLikes); const [liked, setLiked] = useState(initialLiked); const [comments, setComments] = useState(initialComments); const [body, setBody] = useState(""); const [error, setError] = useState<string | null>(null);
  async function toggleLike() { if (!signedIn) { setError("Sign in to like artwork."); return; } const r = await fetch(`/api/art/${artworkId}/like`, { method: "POST" }); const d = await r.json() as { liked?: boolean; count?: number }; if (r.ok) { setLiked(Boolean(d.liked)); setLikes(d.count ?? likes); } }
  async function comment(event: FormEvent) { event.preventDefault(); if (!signedIn) { setError("Sign in to join the conversation."); return; } const r = await fetch(`/api/art/${artworkId}/comments`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ body }) }); const d = await r.json() as Comment & { error?: string }; if (!r.ok) { setError(d.error ?? "Unable to post comment."); return; } setComments([...comments, d]); setBody(""); setError(null); }
  return <section className="border-t border-stone-200 pt-5"><div className="flex items-center gap-3"><button onClick={toggleLike} className={`rounded-full px-4 py-2 text-sm font-medium ${liked ? "bg-rose-50 text-rose-700" : "bg-stone-100 text-stone-700"}`}>{liked ? "♥ Liked" : "♡ Like"} · {likes}</button><span className="text-sm text-stone-500">{comments.length} comments</span></div><div className="mt-5 space-y-3">{comments.map(comment => <div key={comment.id} className="text-sm"><span className="font-medium text-stone-900">{comment.user.displayName}</span><span className="ml-2 text-stone-600">{comment.body}</span></div>)}</div><form onSubmit={comment} className="mt-4 flex gap-2"><input value={body} onChange={e => setBody(e.target.value)} maxLength={500} placeholder={signedIn ? "Leave a thoughtful comment" : "Sign in to comment"} className="min-w-0 flex-1 rounded-xl border border-stone-300 px-3 py-2 text-sm" /><button className="rounded-xl bg-stone-900 px-3 text-sm font-medium text-white">Post</button></form>{error && <p className="mt-2 text-sm text-rose-700">{error}</p>}</section>;
}
